//global actions
export const DISPLAY_ALERT = 'SHOW_ALERT'
export const CLEAR_ALERT = 'CLEAR_ALERT'

export const HANDLE_CHANGE = 'HANDLE_CHANGE'
export const CLEAR_VALUES = 'CLEAR_VALUES'

export const CLEAR_FILTERS = 'CLEAR_FILTERS'
export const CHANGE_PAGE = 'CHANGE_PAGE'

export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR'


//user actions
export const SETUP_USER_BEGIN = 'SETUP_USER_BEGIN'
export const SETUP_USER_SUCCESS = 'SETUP_USER_SUCCESS'
export const SETUP_USER_ERROR = 'SETUP_USER_ERROR'


export const LOGOUT_USER = 'LOGOUT_USER'

export const UPDATE_USER_BEGIN = 'UPDATE_USER_BEGIN'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR'


//project actions
export const CREATE_PROJECT_BEGIN = 'CREATE_PROJECT_BEGIN'
export const CREATE_PROJECT_SUCCESS = 'CREATE_PROJECT_SUCCESS'
export const CREATE_PROJECT_ERROR = 'CREATE_PROJECT_ERROR'

export const GET_PROJECTS_BEGIN = 'GET_PROJECTS_BEGIN'
export const GET_PROJECTS_SUCCESS = 'GET_PROJECTS_SUCCESS'


export const GET_SINGLE_PROJECT = 'GET_SINGLE_PROJECT'


export const SET_EDIT_PROJECT = 'SET_EDIT_PROJECT'


export const DELETE_PROJECT_BEGIN = 'DELETE_PROJECT_BEGIN'

export const EDIT_PROJECT_BEGIN = 'EDIT_PROJECT_BEGIN'
export const EDIT_PROJECT_SUCCESS = 'EDIT_PROJECT_SUCCESS'
export const EDIT_PROJECT_ERROR = 'EDIT_PROJECT_ERROR'


//statistic action
export const SHOW_STATS_BEGIN = 'SHOW_STATS_BEGIN'
export const SHOW_STATS_SUCCESS = 'SHOW_STATS_SUCCESS'


